package com.apiforge.service;

import com.apiforge.model.ApiForgeResponse;
import com.apiforge.model.EndpointInfo;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.net.URI;

@Service
@Slf4j
public class GeneratorService {

    public String generateJavaWrapper(ApiForgeResponse response, String apiName) {
        log.info("Generating Java wrapper for API: {}", apiName);

        if (response == null || response.getEndpoints() == null) {
            log.warn("No endpoints found in response for API: {}", apiName);
            return "// No endpoints found";
        }

        if (response.getEndpoints().isEmpty()) {
            log.warn("Empty endpoints list for API: {}", apiName);
            return "// No endpoints found";
        }

        StringBuilder code = new StringBuilder();
        String className = generateClassName(apiName);
        String baseUrl = response.getBaseUrl() != null ? response.getBaseUrl() : "https://api.example.com";
        String authMethod = response.getAuthMethod() != null ? response.getAuthMethod() : "Bearer Token";

        // Class header comment
        code.append("// Auto-generated by APIForge\n");
        code.append("// API: ").append(apiName).append("\n\n");

        // Imports
        code.append("import java.net.URI;\n");
        code.append("import java.net.http.HttpClient;\n");
        code.append("import java.net.http.HttpRequest;\n");
        code.append("import java.net.http.HttpResponse;\n\n");

        // Class declaration
        code.append("public class ").append(className).append(" {\n\n");

        // Fields
        code.append("    private final String BASE_URL = \"").append(baseUrl).append("\";\n");
        code.append("    private final String apiKey;\n");
        code.append("    private final HttpClient client;\n\n");

        // Constructor
        code.append("    public ").append(className).append("(String apiKey) {\n");
        code.append("        this.apiKey = apiKey;\n");
        code.append("        this.client = HttpClient.newHttpClient();\n");
        code.append("    }\n\n");

        // Generate methods for each endpoint
        for (EndpointInfo endpoint : response.getEndpoints()) {
            generateEndpointMethod(code, endpoint, authMethod);
        }

        // Main method with example usage
        generateMainMethod(code, className, response.getEndpoints().get(0));

        // Close class
        code.append("}\n");

        log.info("Successfully generated Java wrapper with {} methods", response.getEndpoints().size());
        return code.toString();
    }

    private void generateEndpointMethod(StringBuilder code, EndpointInfo endpoint, String authMethod) {
        String methodName = generateMethodName(endpoint.getEndpoint());
        String httpMethod = endpoint.getMethod().toUpperCase();
        String description = endpoint.getDescription() != null ? endpoint.getDescription() : "API endpoint";

        // Method comment
        code.append("    /**\n");
        code.append("     * ").append(description).append("\n");
        code.append("     * Endpoint: ").append(endpoint.getEndpoint()).append("\n");
        code.append("     * Method: ").append(httpMethod).append("\n");
        code.append("     */\n");

        // Method signature
        code.append("    public String ").append(methodName).append("() throws Exception {\n");

        // Build request
        code.append("        HttpRequest.Builder requestBuilder = HttpRequest.newBuilder()\n");
        code.append("            .uri(URI.create(BASE_URL + \"").append(endpoint.getEndpoint()).append("\"))\n");

        // Add authorization header based on auth method
        if (authMethod.toLowerCase().contains("bearer")) {
            code.append("            .header(\"Authorization\", \"Bearer \" + apiKey)\n");
        } else if (authMethod.toLowerCase().contains("api key")) {
            code.append("            .header(\"X-API-Key\", apiKey)\n");
        } else {
            code.append("            .header(\"Authorization\", apiKey)\n");
        }

        code.append("            .header(\"Content-Type\", \"application/json\")\n");

        // HTTP method
        switch (httpMethod) {
            case "GET":
                code.append("            .GET();\n");
                break;
            case "POST":
                code.append("            .POST(HttpRequest.BodyPublishers.ofString(\"{}\"));\n");
                break;
            case "PUT":
                code.append("            .PUT(HttpRequest.BodyPublishers.ofString(\"{}\"));\n");
                break;
            case "DELETE":
                code.append("            .DELETE();\n");
                break;
            default:
                code.append("            .GET();\n");
        }

        code.append("\n");
        code.append("        HttpRequest request = requestBuilder.build();\n");
        code.append("        HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());\n");
        code.append("        return response.body();\n");
        code.append("    }\n\n");
    }

    private void generateMainMethod(StringBuilder code, String className, EndpointInfo firstEndpoint) {
        String firstMethodName = generateMethodName(firstEndpoint.getEndpoint());

        code.append("    /**\n");
        code.append("     * Example usage\n");
        code.append("     */\n");
        code.append("    public static void main(String[] args) {\n");
        code.append("        try {\n");
        code.append("            // Create wrapper instance with your API key\n");
        code.append("            ").append(className).append(" api = new ").append(className).append("(\"your-api-key-here\");\n\n");
        code.append("            // Call the API endpoint\n");
        code.append("            String response = api.").append(firstMethodName).append("();\n");
        code.append("            System.out.println(\"Response: \" + response);\n\n");
        code.append("        } catch (Exception e) {\n");
        code.append("            System.err.println(\"Error calling API: \" + e.getMessage());\n");
        code.append("            e.printStackTrace();\n");
        code.append("        }\n");
        code.append("    }\n");
    }

    private String generateMethodName(String endpoint) {
        // Convert endpoint path to method name
        // e.g., "/users/profile" -> "getUsersProfile"
        // e.g., "/api/v1/data" -> "getApiV1Data"
        
        String[] parts = endpoint.split("/");
        StringBuilder methodName = new StringBuilder("get");
        
        for (String part : parts) {
            if (!part.isEmpty() && !part.matches("\\{.*\\}")) {
                methodName.append(capitalizeFirstLetter(part));
            }
        }
        
        // If the method name is just "get", make it more descriptive
        if (methodName.toString().equals("get")) {
            methodName.append("Data");
        }
        
        return methodName.toString();
    }

    private String generateClassName(String apiName) {
        String nameSource = apiName;

        try {
            URI uri = URI.create(apiName);
            String host = uri.getHost();
            String path = uri.getPath();

            if (host != null && !host.isBlank()) {
                host = host.replaceFirst("^www\\.", "");
                String[] hostParts = host.split("\\.");
                nameSource = hostParts.length > 0 ? hostParts[0] : host;

                if (path != null && !path.isBlank()) {
                    String[] pathParts = path.split("/");
                    for (int i = pathParts.length - 1; i >= 0; i--) {
                        if (!pathParts[i].isBlank()) {
                            nameSource += " " + pathParts[i];
                            break;
                        }
                    }
                }
            }
        } catch (IllegalArgumentException ignored) {
            // Fall back to sanitizing the original text below.
        }

        String[] parts = nameSource.replaceAll("[^A-Za-z0-9]+", " ").trim().split("\\s+");
        StringBuilder className = new StringBuilder();

        for (String part : parts) {
            if (!part.isBlank()) {
                className.append(capitalizeFirstLetter(part));
            }
        }

        if (className.isEmpty()) {
            className.append("Api");
        }

        if (!Character.isJavaIdentifierStart(className.charAt(0))) {
            className.insert(0, "Api");
        }

        return className.append("Wrapper").toString();
    }

    private String capitalizeFirstLetter(String str) {
        if (str == null || str.isEmpty()) {
            return str;
        }
        return str.substring(0, 1).toUpperCase() + str.substring(1);
    }
}
